# Generated by Django 5.2.7 on 2025-10-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Is Confirmed'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
    ]
