# Generated by Django 5.2.7 on 2025-10-02 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch name')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100, verbose_name='District name')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Equipment name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, unique=True, verbose_name='Region name')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Specialist title')),
            ],
            options={
                'verbose_name': 'Specialist',
                'verbose_name_plural': 'Specialists',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Specialty name')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('paternal_name', models.CharField(max_length=128, verbose_name='Paternal name')),
                ('full_address', models.CharField(max_length=255, verbose_name='Full address')),
                ('phone_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99001112233'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,13}$')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('document_type', models.CharField(max_length=50, verbose_name='Document type')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Document file')),
                ('registration_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Registration number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='ApplicationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Application')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.branch', verbose_name='Branch')),
                ('selected_equipment', models.ManyToManyField(blank=True, to='applications.equipment', verbose_name='Selected Equipment')),
                ('selected_specialists', models.ManyToManyField(blank=True, to='applications.specialist', verbose_name='Selected Specialists')),
                ('specialties', models.ManyToManyField(to='applications.specialty', verbose_name='Specialties')),
            ],
            options={
                'verbose_name': 'Applications Branch',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='branches',
            field=models.ManyToManyField(through='applications.ApplicationBranch', to='applications.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='applications.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='EquipmentRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.specialty', verbose_name='Specialty')),
            ],
            options={
                'verbose_name': 'Equipment Required',
                'verbose_name_plural': 'Equipments Required',
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveIntegerField(default=1, verbose_name='Minimum count')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.equipment', verbose_name='Equipment')),
                ('equipment_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applications.equipmentrequired', verbose_name='Equipment Required')),
            ],
            options={
                'verbose_name': 'Equipment Required Item',
                'verbose_name_plural': 'Equipment Required Items',
                'unique_together': {('equipment_required', 'equipment')},
            },
        ),
        migrations.CreateModel(
            name='SpecialistsRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveIntegerField(default=1, verbose_name='Minimum count')),
                ('required_specialists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.specialist', verbose_name='Minimum required specialists')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.specialty', verbose_name='Specialty')),
            ],
            options={
                'verbose_name': 'Specialist Required',
                'verbose_name_plural': 'Specialists Required',
                'unique_together': {('specialty', 'required_specialists')},
            },
        ),
    ]
