# Generated by Django 5.2.7 on 2025-10-06 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationbranch',
            options={'verbose_name': 'Application Branch', 'verbose_name_plural': 'Applications Branch'},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_id_9457c8_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationbranch',
            index=models.Index(fields=['application'], name='application_applica_c1e4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationbranch',
            index=models.Index(fields=['branch'], name='application_branch__d62c98_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['district'], name='application_distric_643699_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['branch_name'], name='application_branch__b8abdb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['name'], name='application_name_ae352b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentrequireditem',
            index=models.Index(fields=['equipment_required'], name='application_equipme_f75c18_idx'),
        ),
        migrations.AddIndex(
            model_name='specialist',
            index=models.Index(fields=['title'], name='application_title_831e51_idx'),
        ),
        migrations.AddIndex(
            model_name='specialistsrequired',
            index=models.Index(fields=['specialty'], name='application_special_8d790f_idx'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['name'], name='application_name_9eb263_idx'),
        ),
    ]
